Stylelint anpassung (#121)
ZooRoyal/coding-standard pull request #125
Opened 2021-02-18 09:31 UTC by rdss-hmorsi

* added css,scss and sass file extensions to stylelint glob pattern
* removed stylelint order plugin
* updated stylelint to 13.9.0
* added stylelint-scss plugin
* removed unused stylelintignore file

2021-02-18 15:16 UTC, rdss-sknott requested changes

2021-02-18 15:16 UTC, rdss-sknott commented on tests/System/Stylelint/RunStylelintWithConfig.php
> +    protected function setUp(): void
Die Methode braucht man hier nicht

2021-02-18 16:37 UTC, rdss-hmorsi commented on tests/System/Stylelint/RunStylelintWithConfig.php
> +    protected function setUp(): void
methode is raus

2021-02-18 16:48 UTC, rdss-sknott approved these changes

2021-02-19 08:47 UTC, rdss-sknott approved these changes

2021-02-19 09:06 UTC, rdss-jpupeter approved these changes

2021-02-19 12:14 UTC, merged