Adding plugin and project directories to the PHPStan autoloading
ZooRoyal/coding-standard pull request #139
Opened 2021-05-21 09:55 UTC by rdss-sknott

* Extended the PHPStan config generator with scanDir entry
* The directories `/Plugins`, `custome/project`, `custome/plugin` are now
  autoloaded by PHPStan

2021-05-21 13:05 UTC, rdss-pwacht approved these changes

2021-05-21 13:42 UTC, rdss-sschomberg requested changes

2021-05-21 13:42 UTC, rdss-sschomberg commented on tests/Unit/CommandLine/StaticCodeAnalysis/PHPStan/PHPStanConfigGeneratorTest.php
> +                H::hasItem($this->mockedRootDirectory . '/custom/project'),
Fehlt hier nicht '/custom/plugins' ?

2021-05-21 13:47 UTC, rdss-sschomberg approved these changes

2021-05-24 08:27 UTC, jhofm approved these changes

2021-05-25 07:21 UTC, merged