adding stencil eslint plugin
ZooRoyal/coding-standard pull request #173
Opened 2022-08-03 14:34 UTC by rdss-mkanzler

Stencil in Coding Standard

2022-08-04 07:51 UTC, rdss-sknott requested changes

2022-08-04 07:51 UTC, rdss-sknott commented on config/eslint/.eslintrc.js
> +                'no-undef': 'off',
*starkes-strinrunzeln* warum sollten wir das so machen?

2022-08-09 06:58 UTC, rdss-mhoevelmanns approved these changes

2022-08-09 14:53 UTC, rdss-mhoevelmanns approved these changes

2022-08-09 15:54 UTC, rdss-sknott requested changes

2022-08-10 07:47 UTC, rdss-sknott approved these changes

2022-08-10 07:50 UTC, rdss-sknott requested changes

2022-08-10 07:50 UTC, rdss-sknott commented on pnpm-lock.yaml
> +lockfileVersion: 5.4
Lock files bitte in die gitignore und nicht commiten

2022-08-10 08:34 UTC, rdss-sknott approved these changes

2022-08-10 08:34 UTC, rdss-mhoevelmanns approved these changes

2022-08-10 08:41 UTC, merged